- hosts: ipharm
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Project directory
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Copy docker-compose
      copy:
        src: docker-compose.yml
        dest: "{{ project_dir + '/docker-compose.yml' }}"

    - name: Create envs directory
      file:
        path: "{{ project_dir + '/.envs/.production'}}"
        state: directory

    - name: Copy envs
      copy:
        src: "{{ item }}"
        dest: "{{ project_dir + '/.envs/.production/' }}"
      with_items:
        - ./.envs/.production/.ipharm_app
        - ./.envs/.production/.ipharm_postgres
        - ./.envs/.production/.nginx

    - name: Create ngingx directory
      file:
        path: "{{ project_dir + '/nginx'}}"
        state: directory

    - name: Copy nginx config
      copy:
        src: nginx/default.conf
        dest: "{{ project_dir + '/nginx'}}"

    - name: Up
      become: yes
      docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        pull: yes

