- hosts: ipharm-demo
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Project directory
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Copy docker-compose
      copy:
        src: docker-compose.demo.yml
        dest: "{{ project_dir + '/docker-compose.yml' }}"

    - name: Create config directory
      file:
        path: "{{ project_dir + '/nginx'}}"
        state: directory

    - name: Copy config files
      copy:
        src: "{{ item }}"
        dest: "{{ project_dir + '/config/' }}"
      with_items:
        - ./config/nginx-config.conf
        - ./config/promtail-config.yml

    - name: Clean frontend
      become: yes
      file:
        path: "{{ project_dir + '/frontend/build'}}"
        state: absent

    - name: Up
      become: yes
      docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        recreate: always
        remove_orphans: yes
        pull: yes

