- hosts: ipharm-demo
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Project directory
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Copy docker-compose
      copy:
        src: docker-compose.demo.yml
        dest: "{{ project_dir + '/docker-compose.yml' }}"

    - name: Create ngingx directory
      file:
        path: "{{ project_dir + '/nginx'}}"
        state: directory

    - name: Copy nginx config
      copy:
        src: nginx/default.conf
        dest: "{{ project_dir + '/nginx'}}"

    - name: Clean frontend
      become: yes
      file:
        path: "{{ project_dir + '/frontend/build'}}"
        state: absent

    - name: Up
      become: yes
      docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        pull: yes

