version: "3"
services:
  ipharm-app:
    container_name: ipharm_app
    image: conceptica/ipharm_app:test
    depends_on:
      - ipharm-postgres
    env_file: &envs-ipharm-app
      - .envs/.production/.ipharm_app
      - .envs/.production/.ipharm_postgres
      - .envs/.production/.ipharm_redis
    ports:
      - "8000:8000"
    command: scripts/start_production.sh
    volumes:
      - ./ipharm_static:/app/static
      - ./ipharm_media:/app/media

  ipharm-worker:
    container_name: ipharm_worker
    image: conceptica/ipharm_app:test
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_worker.sh

  ipharm-beat:
    container_name: ipharm_beat
    image: conceptica/ipharm_app:test
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_beat.sh

  ipharm-postgres:
    container_name: ipharm_postgres
    image: postgres:13.4-alpine
    env_file:
      - .envs/.production/.ipharm_postgres
    volumes:
      - ./_postgres_data_ipharm:/var/lib/postgresql/data

  ipharm-redis:
    container_name: ipharm_redis
    image: redis:6.2-alpine

  ipharm-flower:
    image: mher/flower
    container_name: ipharm_flower
    env_file:
      -  .envs/.production/.ipharm_redis
    ports:
      - "5555:5555"
    depends_on:
      - ipharm-redis

  iciselniky-app:
    container_name: iciselniky_app
    image: conceptica/iciselniky_app:test
    depends_on:
      - iciselniky-postgres
    env_file: &envs-iciselniky-app
      - .envs/.production/.iciselniky_app
      - .envs/.production/.iciselniky_postgres
      - .envs/.production/.iciselniky_redis
    ports:
      - "8001:8000"
    command: scripts/start_production.sh
    volumes: &volumes-iciselniky-app
      - ./iciselniky_static:/app/static

  iciselniky-postgres:
    container_name: iciselniky_postgres
    image: postgres:13.4-alpine
    env_file:
      - .envs/.production/.iciselniky_postgres
    volumes:
      - ./_postgres_data_iciselniky:/var/lib/postgresql/data

  iciselniky-worker:
    container_name: iciselniky_worker
    image: conceptica/iciselniky_app:test
    volumes: *volumes-iciselniky-app
    depends_on:
      - iciselniky-postgres
      - iciselniky-redis
      - iciselniky-app
    env_file: *envs-iciselniky-app
    command: scripts/start_worker.sh

  iciselniky-beat:
    container_name: iciselniky_beat
    image: conceptica/iciselniky_app:test
    volumes: *volumes-iciselniky-app
    depends_on:
      - iciselniky-postgres
      - iciselniky-redis
      - iciselniky-app
    env_file: *envs-iciselniky-app
    command: scripts/start_beat.sh

  iciselniky-redis:
    container_name: iciselniky_redis
    image: redis:6.2-alpine

  iciselniky-flower:
    image: mher/flower
    container_name: iciselniky_flower
    env_file:
      -  .envs/.production/.iciselniky_redis
    ports:
      - "5556:5555"
    depends_on:
      - iciselniky-redis

  frontend-app:
    container_name: frontend_app
    image: conceptica/ipharm_fe_app:test
    command: cp -r ./build /frontend
    volumes:
      - ./frontend:/frontend

  nginx:
    container_name: ipharm_nginx
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template
      - ./ipharm_static:/ipharm_static
      - ./ipharm_media:/ipharm_media
      - ./iciselniky_static:/iciselniky_static
      - ./frontend/:/frontend
    env_file:
      - .envs/.production/.nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ipharm-app
      - iciselniky-app
      - frontend-app
