version: "3.7"

services:

  promtail:
    image: grafana/promtail:2.4.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config/promtail-config.yml:/mnt/config/promtail-config.yml
      - {{ docker_data_dir }}:/host/containers
    command: -config.file /mnt/config/promtail-config.yml
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
    env_file:
      - .envs/.production/.grafana
    networks:
      - external
      - default

volumes:
  grafana_storage:
  loki_data:

networks:
  external:
    name: ipharm-network
