version: "3.7"

services:
  ipharm-app:
    image: conceptica/ipharm_app:{{docker_be_tag}}
    container_name: ipharm-app
    restart: unless-stopped
    depends_on:
      - ipharm-postgres
    env_file: &envs-ipharm-app
      - .envs/.production/.ipharm_app
      - .envs/.production/.ipharm_postgres
      - .envs/.production/.ipharm_redis
    logging: &logging
      driver: "json-file"
      options:
        tag: {{ '"{{.ImageName}}|{{.Name}}"' }}
    command: scripts/start_production.sh
    volumes:
      - ./ipharm_static:/app/static
      - ./ipharm_media:/app/media
    networks:
      - external
      - default

  ipharm-worker-high-priority:
    image: conceptica/ipharm_app:{{docker_be_tag}}
    container_name: ipharm-worker-high-priority
    restart: unless-stopped
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    logging: *logging
    command: scripts/start_worker.sh -Q high_priority -n high_priority
    volumes:
      - ./ipharm_media:/app/media

  ipharm-worker-medium-priority:
    image: conceptica/ipharm_app:{{docker_be_tag}}
    container_name: ipharm-worker-medium-priority
    restart: unless-stopped
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    logging: *logging
    command: scripts/start_worker.sh -Q medium_priority -n medium_priority
    volumes:
      - ./ipharm_media:/app/media

  ipharm-worker-low-priority:
    image: conceptica/ipharm_app:{{docker_be_tag}}
    container_name: ipharm-worker-low-priority
    restart: unless-stopped
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    logging: *logging
    command: scripts/start_worker.sh -Q low_priority -n low_priority
    volumes:
      - ./ipharm_media:/app/media

  ipharm-beat:
    image: conceptica/ipharm_app:{{docker_be_tag}}
    container_name: ipharm-beat
    restart: unless-stopped
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    logging: *logging
    command: scripts/start_beat.sh

  ipharm-postgres:
    image: postgres:13.4-alpine
    container_name: ipharm-postgres
    restart: unless-stopped
    env_file:
      - .envs/.production/.ipharm_postgres
    logging: *logging
    volumes:
      - ./_postgres_data_ipharm:/var/lib/postgresql/data

  ipharm-redis:
    image: redis:6.2-alpine
    container_name: ipharm-redis
    restart: unless-stopped
    logging: *logging

  ipharm-flower:
    image: mher/flower
    container_name: ipharm-flower
    restart: unless-stopped
    env_file:
      - .envs/.production/.ipharm_redis
    logging: *logging
    depends_on:
      - ipharm-redis
    networks:
      - external
      - default

  ipharm-frontend-app:
    image: conceptica/ipharm_fe_app:{{docker_fe_tag}}
    container_name: ipharm-frontend-app
    command: cp -r ./build /frontend
    logging: *logging
    volumes:
      - ./frontend_ipharm:/frontend

networks:
  external:
    name: ipharm-network