name: Deploy test

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update
      - name: Install ansible
        run: sudo apt-get install ansible
      - name: Install openvpn
        run: sudo apt-get install openvpn -y
      - name: Create openvpn config
        run: echo "${{ secrets.VPN_CONFIG }}" >>  vpnconfig.ovpn
      - name:  Create env files
        run: |
          mkdir -p .envs/.production
          touch .envs/.production/.ipharm_app
          echo "SECRET_KEY=${{ secrets.TEST_IPHARM_SECRET_KEY }}" >>  .envs/.production/.ipharm_app
          echo "ALLOWED_HOSTS=${{ secrets.TEST_IPHARM_DOMAIN }}" >>  .envs/.production/.ipharm_app
          echo "SENTRY_DSN=${{ secrets.TEST_IPHARM_SENTRY_DSN }}" >>  .envs/.production/.ipharm_app
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.TEST_CORS_ALLOWED_ORIGINS }}" >>  .envs/.production/.ipharm_app
          echo SENTRY_ENVIRONMENT=test >>  .envs/.production/.ipharm_app
          echo ENVIRONMENT=test >>  .envs/.production/.ipharm_app
          echo LOG_LEVEL=DEBUG >>  .envs/.production/.ipharm_app
          echo "BASE_ICISELNIKY_URL=${{ secrets.TEST_IPHARM_BASE_ICISELNIKY_URL }}" >>  .envs/.production/.ipharm_app
          echo "ICISELNIKY_TOKEN=${{ secrets.TEST_IPHARM_ICISELNIKY_TOKEN }}" >>  .envs/.production/.ipharm_app
          touch .envs/.production/.ipharm_postgres
          echo POSTGRES_HOST=ipharm-postgres >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_PORT=5432 >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_DB=ipharm >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_USER=ipharm >>  .envs/.production/.ipharm_postgres
          echo "POSTGRES_PASSWORD=${{ secrets.TEST_IPHARM_POSTGRES_PASSWORD }}" >>  .envs/.production/.ipharm_postgres
          touch .envs/.production/.ipharm_redis
          echo REDIS_HOST=ipharm-redis >>  .envs/.production/.ipharm_redis
          echo REDIS_PORT=6379 >>  .envs/.production/.ipharm_redis
          echo CELERY_BROKER_URL=redis://ipharm-redis:6379/1 >>  .envs/.production/.ipharm_redis
          echo "FLOWER_BASIC_AUTH=${{ secrets.TEST_IPHARM_FLOWER_AUTH }}" >>  .envs/.production/.ipharm_redis
          touch .envs/.production/.iciselniky_app
          echo "SECRET_KEY=${{ secrets.TEST_ICISELNIKY_SECRET_KEY }}" >>  .envs/.production/.iciselniky_app
          echo "ALLOWED_HOSTS=${{ secrets.TEST_ICISELNIKY_DOMAIN }}" >>  .envs/.production/.iciselniky_app
          echo "SENTRY_DSN=${{ secrets.TEST_ICISELNIKY_SENTRY_DSN }}" >>  .envs/.production/.iciselniky_app
          echo SENTRY_ENVIRONMENT=test >>  .envs/.production/.iciselniky_app
          echo LOG_LEVEL=DEBUG >>  .envs/.production/.iciselniky_app
          touch .envs/.production/.iciselniky_postgres
          echo POSTGRES_HOST=iciselniky-postgres >>  .envs/.production/.iciselniky_postgres
          echo POSTGRES_PORT=5432 >>  .envs/.production/.iciselniky_postgres
          echo POSTGRES_DB=iciselniky >>  .envs/.production/.iciselniky_postgres
          echo POSTGRES_USER=iciselniky >>  .envs/.production/.iciselniky_postgres
          echo "POSTGRES_PASSWORD=${{ secrets.TEST_ICISELNIKY_POSTGRES_PASSWORD }}" >>  .envs/.production/.iciselniky_postgres
          touch .envs/.production/.iciselniky_redis
          echo REDIS_HOST=iciselniky-redis >>  .envs/.production/.iciselniky_redis
          echo REDIS_PORT=6379 >>  .envs/.production/.iciselniky_redis
          echo CELERY_BROKER_URL=redis://iciselniky-redis:6379/1 >>  .envs/.production/.iciselniky_redis
          touch .envs/.production/.izadanky_app
          echo "SECRET_KEY=${{ secrets.TEST_IZADANKY_SECRET_KEY }}" >>  .envs/.production/.izadanky_app
          echo "ALLOWED_HOSTS=${{ secrets.TEST_IZADANKY_DOMAIN }}" >>  .envs/.production/.izadanky_app
          echo "SENTRY_DSN=${{ secrets.TEST_IZADANKY_SENTRY_DSN }}" >>  .envs/.production/.izadanky_app
          echo SENTRY_ENVIRONMENT=test >>  .envs/.production/.izadanky_app
          echo LOG_LEVEL=DEBUG >>  .envs/.production/.izadanky_app
          echo "BASE_IPHARM_URL=${{ secrets.TEST_IZADANKY_BASE_IPHARM_URL }}" >>  .envs/.production/.izadanky_app
          echo "IPHARM_TOKEN=${{ secrets.TEST_IZADANKY_IPHARM_TOKEN }}" >>  .envs/.production/.izadanky_app
          echo "BASE_ICISELNIKY_URL=${{ secrets.TEST_IZADANKY_BASE_ICISELNIKY_URL }}" >>  .envs/.production/.izadanky_app
          echo "ICISELNIKY_TOKEN=${{ secrets.TEST_IZADANKY_ICISELNIKY_TOKEN }}" >>  .envs/.production/.izadanky_app
          touch .envs/.production/.izadanky_postgres
          echo POSTGRES_HOST=izadanky-postgres >>  .envs/.production/.izadanky_postgres
          echo POSTGRES_PORT=5432 >>  .envs/.production/.izadanky_postgres
          echo POSTGRES_DB=izadanky >>  .envs/.production/.izadanky_postgres
          echo POSTGRES_USER=izadanky >>  .envs/.production/.izadanky_postgres
          echo "POSTGRES_PASSWORD=${{ secrets.TEST_IZADANKY_POSTGRES_PASSWORD }}" >>  .envs/.production/.izadanky_postgres
          touch .envs/.production/.izadanky_redis
          echo REDIS_HOST=izadanky-redis >>  .envs/.production/.izadanky_redis
          echo REDIS_PORT=6379 >>  .envs/.production/.izadanky_redis
          echo CELERY_BROKER_URL=redis://izadanky-redis:6379/1 >>  .envs/.production/.izadanky_redis
          touch .envs/.production/.nginx
          echo "IPHARM_DOMAIN=${{ secrets.TEST_IPHARM_DOMAIN }}" >>  .envs/.production/.nginx
          echo "ICISELNIKY_DOMAIN=${{ secrets.TEST_ICISELNIKY_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IPHARM_FRONTEND_DOMAIN=${{ secrets.TEST_IPHARM_FRONTEND_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IZADANKY_DOMAIN=${{ secrets.TEST_IZADANKY_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IZADANKY_FRONTEND_DOMAIN=${{ secrets.TEST_IZADANKY_FRONTEND_DOMAIN }}" >>  .envs/.production/.nginx
          echo "GRAFANA_DOMAIN=${{ secrets.TEST_GRAFANA_DOMAIN }}" >>  .envs/.production/.nginx
          echo "GRAFANA_PORT=${{ secrets.TEST_GRAFANA_PORT }}" >>  .envs/.production/.nginx
          echo "IPHARM_FLOWER_DOMAIN=${{ secrets.TEST_IPHARM_FLOWER_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IPHARM_FLOWER_PORT=${{ secrets.TEST_IPHARM_FLOWER_PORT }}" >>  .envs/.production/.nginx
          echo "ICISELNIKY_FLOWER_DOMAIN=${{ secrets.TEST_ICISELNIKY_FLOWER_DOMAIN }}" >>  .envs/.production/.nginx
          echo "ICISELNIKY_FLOWER_PORT=${{ secrets.TEST_ICISELNIKY_FLOWER_PORT }}" >>  .envs/.production/.nginx
          echo "IZADANKY_FLOWER_DOMAIN=${{ secrets.TEST_IZADANKY_FLOWER_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IZADANKY_FLOWER_PORT=${{ secrets.TEST_IZADANKY_FLOWER_PORT }}" >>  .envs/.production/.nginx
          touch .envs/.production/.grafana
          echo "GF_SECURITY_ADMIN_USER=${{ secrets.TEST_GF_SECURITY_ADMIN_USER }}" >>  .envs/.production/.grafana
          echo "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.TEST_GF_SECURITY_ADMIN_PASSWORD }}" >>  .envs/.production/.grafana
      - name: Create key
        run: |
          mkdir ~/.ssh/
          touch ~/.ssh/ed25519
          chmod 600 ~/.ssh/ed25519
          echo "${{ secrets.TEST_PRIVATE_KEY }}" >>  ~/.ssh/ed25519
      - name: Create ansible inventory file
        run: |
          touch hosts
          echo "[ipharm-test]" >> hosts
          echo "${{ secrets.TEST_HOST }} ansible_user=${{ secrets.TEST_USER }} ansible_ssh_private_key_file=~/.ssh/ed25519 project_dir=${{ secrets.TEST_PROJECT_DIRECTORY }}" >> hosts
      - name: Run openvpn
        run: |
          sudo openvpn --config vpnconfig.ovpn --daemon
      - name: Wait openvpn connection
        timeout-minutes: 1
        run: until ping -c1 ${{ secrets.TEST_HOST }}; do sleep 2; done

      - name: Deploy
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts -v deploy_test.yml
