# This is a basic workflow that is manually triggered

name: Deploy test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install ansible
        run: sudo apt-get install ansible
      - name:  Create env files
        run: |
          mkdir -p .envs/.production
          touch .envs/.production/.ipharm_app
          echo "SECRET_KEY=${{ secrets.TEST_IPHARM_SECRET_KEY_DEV }}" >>  .envs/.production/.ipharm_app
          echo "ALLOWED_HOSTS=${{ secrets.TEST_IPHARM_ADMIN_DOMAIN }},${{ secrets.TEST_IPHARM_API_DOMAIN }}" >>  .envs/.production/.ipharm_app
          touch .envs/.production/.ipharm_postgres
          echo POSTGRES_HOST=ipharm_postgres >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_PORT=5432 >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_DB=ipharm >>  .envs/.production/.ipharm_postgres
          echo POSTGRES_USER=ipharm >>  .envs/.production/.ipharm_postgres
          echo "POSTGRES_PASSWORD=${{ secrets.TEST_IPHARM_POSTGRES_PASSWORD }}" >>  .envs/.production/.ipharm_postgres
          touch .envs/.production/.nginx
          echo "IPHARM_ADMIN_DOMAIN=${{ secrets.TEST_IPHARM_ADMIN_DOMAIN }}" >>  .envs/.production/.nginx
          echo "IPHARM_API_DOMAIN=${{ secrets.TEST_IPHARM_API_DOMAIN }}" >>  .envs/.production/.nginx
      - name: Create key
        run: |
          mkdir ~/.ssh/
          touch ~/.ssh/ed25519
          chmod 600 ~/.ssh/ed25519
          echo "${{ secrets.TEST_PRIVATE_KEY }}" >>  ~/.ssh/ed25519
      - name: Create ansible inventory file
        run: |
          touch hosts
          echo "[ipharm]" >> hosts
          echo "${{ secrets.TEST_HOST }} ansible_user=${{ secrets.TEST_USER }} ansible_ssh_private_key_file=~/.ssh/ed25519 project_dir=${{ secrets.TEST_PROJECT_DIRECTORY }}" >> hosts
      - name: Deploy
        run: ansible-playbook -i hosts -v deploy_production.yml
